import type { FontCandidate } from './types'

export const FONT_CANDIDATES: FontCandidate[] = [
  { family: 'Arial', category: 'Sans-serif', faces: ['Arial', 'Arimo'] },
  { family: 'Arial Black', category: 'Display', faces: ['Arial Black'] },
  { family: 'Helvetica', category: 'Sans-serif', faces: ['Helvetica Neue', 'Helvetica'] },
  { family: 'Verdana', category: 'Sans-serif', faces: ['Verdana'] },
  { family: 'Tahoma', category: 'Sans-serif', faces: ['Tahoma'] },
  { family: 'Trebuchet MS', category: 'Sans-serif', faces: ['Trebuchet MS'] },
  { family: 'Calibri', category: 'Sans-serif', faces: ['Calibri', 'Carlito'] },
  { family: 'Segoe UI', category: 'Sans-serif', faces: ['Segoe UI'] },
  { family: 'Geneva', category: 'Sans-serif', faces: ['Geneva'] },
  { family: 'Lucida Sans Unicode', category: 'Sans-serif', faces: ['Lucida Sans Unicode'] },
  { family: 'Roboto', category: 'Sans-serif', faces: ['Roboto'] },
  { family: 'Open Sans', category: 'Sans-serif', faces: ['Open Sans'] },
  { family: 'Lato', category: 'Sans-serif', faces: ['Lato'] },
  { family: 'Montserrat', category: 'Sans-serif', faces: ['Montserrat'] },
  { family: 'Poppins', category: 'Sans-serif', faces: ['Poppins'] },
  { family: 'Raleway', category: 'Sans-serif', faces: ['Raleway'] },
  { family: 'Source Sans 3', category: 'Sans-serif', faces: ['Source Sans 3'] },
  { family: 'Nunito', category: 'Sans-serif', faces: ['Nunito'] },
  { family: 'Fira Sans', category: 'Sans-serif', faces: ['Fira Sans'] },
  { family: 'Ubuntu', category: 'Sans-serif', faces: ['Ubuntu'] },
  { family: 'Work Sans', category: 'Sans-serif', faces: ['Work Sans'] },
  { family: 'Rubik', category: 'Sans-serif', faces: ['Rubik'] },
  { family: 'DM Sans', category: 'Sans-serif', faces: ['DM Sans'] },
  { family: 'Manrope', category: 'Sans-serif', faces: ['Manrope'] },
  { family: 'Mulish', category: 'Sans-serif', faces: ['Mulish'] },
  { family: 'Karla', category: 'Sans-serif', faces: ['Karla'] },
  { family: 'Cabin', category: 'Sans-serif', faces: ['Cabin'] },
  { family: 'Barlow', category: 'Sans-serif', faces: ['Barlow'] },
  { family: 'Barlow Condensed', category: 'Sans-serif', faces: ['Barlow Condensed'] },
  { family: 'Exo 2', category: 'Sans-serif', faces: ['Exo 2'] },
  { family: 'Titillium Web', category: 'Sans-serif', faces: ['Titillium Web'] },
  { family: 'Quicksand', category: 'Sans-serif', faces: ['Quicksand'] },
  { family: 'Josefin Sans', category: 'Sans-serif', faces: ['Josefin Sans'] },
  { family: 'Noto Sans', category: 'Sans-serif', faces: ['Noto Sans'] },
  { family: 'Inter', category: 'Sans-serif', faces: ['Inter'] },
  { family: 'Roboto Slab', category: 'Serif', faces: ['Roboto Slab'] },
  { family: 'Arvo', category: 'Serif', faces: ['Arvo'] },
  { family: 'Bree Serif', category: 'Serif', faces: ['Bree Serif'] },
  { family: 'Cambria', category: 'Serif', faces: ['Cambria', 'Caladea'] },
  { family: 'Times New Roman', category: 'Serif', faces: ['Times New Roman', 'Tinos'] },
  { family: 'Georgia', category: 'Serif', faces: ['Georgia'] },
  { family: 'Garamond', category: 'Serif', faces: ['Garamond', 'EB Garamond'] },
  { family: 'Palatino', category: 'Serif', faces: ['Palatino Linotype', 'Book Antiqua', 'Palatino'] },
  { family: 'Baskerville', category: 'Serif', faces: ['Libre Baskerville', 'Baskerville'] },
  { family: 'Didot', category: 'Serif', faces: ['Didot'] },
  { family: 'Merriweather', category: 'Serif', faces: ['Merriweather'] },
  { family: 'PT Serif', category: 'Serif', faces: ['PT Serif'] },
  { family: 'Playfair Display', category: 'Serif', faces: ['Playfair Display'] },
  { family: 'Lora', category: 'Serif', faces: ['Lora'] },
  { family: 'Noto Serif', category: 'Serif', faces: ['Noto Serif'] },
  { family: 'Zilla Slab', category: 'Serif', faces: ['Zilla Slab'] },
  { family: 'Cormorant Garamond', category: 'Serif', faces: ['Cormorant Garamond'] },
  { family: 'Comic Sans MS', category: 'Display', faces: ['Comic Sans MS', 'Comic Neue', 'Chalkboard SE', 'Chalkboard', 'Marker Felt'] },
  { family: 'Comic Neue', category: 'Display', faces: ['Comic Neue', 'Comic Sans MS', 'Chalkboard SE'] },
  { family: 'Chalkboard', category: 'Display', faces: ['Chalkboard SE', 'Chalkboard', 'Comic Sans MS'] },
  { family: 'Marker Felt', category: 'Display', faces: ['Marker Felt', 'Comic Sans MS'] },
  { family: 'Patrick Hand', category: 'Display', faces: ['Patrick Hand'] },
  { family: 'Gloria Hallelujah', category: 'Display', faces: ['Gloria Hallelujah'] },
  { family: 'Schoolbell', category: 'Display', faces: ['Schoolbell'] },
  { family: 'Handlee', category: 'Display', faces: ['Handlee'] },
  { family: 'Architects Daughter', category: 'Display', faces: ['Architects Daughter'] },
  { family: 'Impact', category: 'Display', faces: ['Impact'] },
  { family: 'Oswald', category: 'Display', faces: ['Oswald'] },
  { family: 'Bebas Neue', category: 'Display', faces: ['Bebas Neue'] },
  { family: 'Anton', category: 'Display', faces: ['Anton'] },
  { family: 'Archivo Black', category: 'Display', faces: ['Archivo Black'] },
  { family: 'Permanent Marker', category: 'Display', faces: ['Permanent Marker'] },
  { family: 'Pacifico', category: 'Display', faces: ['Pacifico'] },
  { family: 'Lobster', category: 'Display', faces: ['Lobster'] },
  { family: 'Amatic SC', category: 'Display', faces: ['Amatic SC'] },
  { family: 'Caveat', category: 'Display', faces: ['Caveat'] },
  { family: 'Indie Flower', category: 'Display', faces: ['Indie Flower'] },
  { family: 'Shadows Into Light', category: 'Display', faces: ['Shadows Into Light'] },
  { family: 'Courier New', category: 'Display', faces: ['Courier New', 'Cousine'] },
  { family: 'Consolas', category: 'Display', faces: ['Consolas'] },
  { family: 'Roboto Mono', category: 'Monospace', faces: ['Roboto Mono'] },
  { family: 'Source Code Pro', category: 'Monospace', faces: ['Source Code Pro'] },
  { family: 'IBM Plex Mono', category: 'Monospace', faces: ['IBM Plex Mono'] },
  { family: 'JetBrains Mono', category: 'Monospace', faces: ['JetBrains Mono'] },
  { family: 'Fira Mono', category: 'Monospace', faces: ['Fira Mono'] },
  { family: 'Inconsolata', category: 'Monospace', faces: ['Inconsolata'] },
  { family: 'Space Mono', category: 'Monospace', faces: ['Space Mono'] },
  { family: 'Ubuntu Mono', category: 'Monospace', faces: ['Ubuntu Mono'] },
  { family: 'Courier Prime', category: 'Monospace', faces: ['Courier Prime'] },
]
